### ISSUE TITLE
import error with jsnext:main

### ISSUE THREAD

**Issue by dr2009** [danbovey/react-infinite-scroller#134]
```
{
 "jsnext:main": "src/InfiniteScroll.js",
}
```
 package.json has `jsnext:main` feild
but in `.npmignore` , `src` has been ignored.

-----
in addition , `.babelrc` should be ignore in `.npmignore` 
because  "add-module-exports" someone like me ,isnot installed

**Comment by danbovey** [comment]
Thanks for the PR.

I don't know much about it but isn't `add-module-exports` a requirement to be able to use `import` and `export`. Let me know how else you do it and I can merge the PR with it being ignored in `.npmignore`.

**Comment by naoyeye** [comment]
> `.babelrc` should be ignore in `.npmignore`

agree. 

ref: https://github.com/CassetteRocks/react-infinite-scroller/issues/99

![image](https://user-images.githubusercontent.com/434428/71764536-e7f25280-2f23-11ea-9d61-99742b0ee37d.png)


I encountered the same error, I should install add-module-exports to build my project:

`yarn add babel-plugin-add-module-exports`

**Comment by danbovey** [comment]
Fixed in #279
