### ISSUE TITLE
[Docs] Please remove hasMore={true || false} from README example

### ISSUE THREAD

**Issue by Cherviakov** [danbovey/react-infinite-scroller#215]
**Describe the bug**
In docs there example with hasMore={true || false}, which meaning is clear, but many people will just copy/paste this code without thinking and then will be surpirsed why their onLoad.

**To Reproduce**
Just copy/paste example code

**Expected behavior**
Should be some meaningfull calculation of hasMore, maybe something like
const hasMore = this.state.messages.length  < this.props.totalMessagesLength;

**Device (please complete the following information):**
 - OS: [e.g. Mac] Linux Ubuntu 16.04
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] react-infinite-scroller@1.2.4

**Comment by QShengW** [comment]
Yes, in loading, load more, load all. A variety of states, not too optimistic
