### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by rhuanbarreto** [danbovey/react-infinite-scroller#250]
**Describe the bug**
The demo page is not working.

**To Reproduce**
Just click on the demo link on README.

**To Fix**
Just use the codesandbox on https://codesandbox.io/s/my6vo3yo78

**Comment by Nagellan** [comment]
@danbovey you should replace the old account name CassetteRocks with the new one wherever used, especially at GitHub Pages links 😊 
So the new correct link will be as follows: https://danbovey.github.io/react-infinite-scroller

**Comment by rhuanbarreto** [comment]
PR is ok to merge @danbovey .

**Comment by danbovey** [comment]
Fixed! Thanks for the PR but didn't use it as it didn't have my custom GitHub domain.
