### ISSUE TITLE
Imports failure while building with Vite

### ISSUE THREAD

**Issue by Emestie** [danbovey/react-infinite-scroller#286]
When using Vite to build React app it says that react-infinite-scroller@1.2.4 has wrong definition of entry point.
Fix is simple - just remove "jsnext:main" key from package.json, since it's targeting src folder that is not present when install via npm. I think changing path there will be working too.

react-infinite-scroller@1.2.4
vite@2.6.14

**Comment by danbovey** [comment]
Fixed in #279
