### ISSUE TITLE
Upgrading to React 18 breaks remove event listeners.

### ISSUE THREAD

**Issue by akhilxnair** [danbovey/react-infinite-scroller#296]
**Describe the bug**
Upgrading to React 18 breaks remove event listeners.

**To Reproduce**
I am using React-18, react-infinite-scroller, and react-router
Let's say I have a react-infinite-scroller on /user-list route. All works fine with scrolling and loading data.
Now when you click on one of the users and go to the next /user-details route, it breaks while trying to remove the old routes event listeners.

**Screenshots**
![image](https://user-images.githubusercontent.com/16269993/163253267-8b5f6583-250a-4158-8a25-d4e926edb4bb.png)
![image](https://user-images.githubusercontent.com/16269993/163253306-2b13003c-a278-455a-bcd2-b92a1fbdcf07.png)

**Device (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 100.0.4896.75 (Official Build) (64-bit)

**Comment by ruipserra** [comment]
I tried reproducing this, but couldn't hit that error. Here's my code: https://github.com/ruipserra/react-infinite-scroller-repro-296

@akhilxnair are you able reproduce the error with my testing code? Can you fork it and change it to hit the error?

**Comment by foreverzwl** [comment]
> 

![image](https://user-images.githubusercontent.com/41141920/164682362-96404098-b69a-428c-b349-7e782ed63880.png)
设置useWindow={false}，就会出现问题

**Comment by yankopetrov** [comment]
The same issue. Not working with react 18.

**Comment by andyogaga** [comment]
> The same issue. Not working with react 18.

Hi, I am facing same issue, were you able to find the solution?

**Comment by akhilxnair** [comment]
@andyogaga Nope, we postponed the upgrade process till everything was stable.
Will try it again in a month.

**Comment by aclarembeau** [comment]
I just tried with useWindow = false and it worked on my end, as suggested by @foreverzwl

**Comment by akhilxnair** [comment]
We upgraded all our packages now and faced no issues this time.
I'll try to find out what fixed the issue, maybe it was fixed by react minor version upgrade.
