### ISSUE TITLE
Pull to refresh not works on latest versions

### ISSUE THREAD

**Issue by YeisonVelez11** [danbovey/react-infinite-scroller#298]
**Describe the bug**

**To Reproduce**

Try do a pull to refresh (scroll top)
https://codesandbox.io/s/beautiful-meitner-kq1my8

**Expected behavior**
the function defined in `refreshFunction` never triggers

**Screenshots**

**Device (please complete the following information):**
 - OS: Mac
 - Browser: chrome
- library version 6.1.0

**Comment by danbovey** [comment]
You're on the wrong repo. Please open an issue for [react-infinite-scroll-component](https://github.com/ankeetmaini/react-infinite-scroll-component)
